plugins {
    id 'java'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id "me.modmuss50.mod-publish-plugin" version "0.8.3"
}

// Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.
def MT_TOKEN = System.getenv("MODRINTH_TOKEN")
def CF_TOKEN = System.getenv("CURSEFORGE_TOKEN")

group = 'com.github.NGoedix.VideoPlayer' // http://maven.apache.org/guides/mini/guide-naming-conventions.html
base {
    archivesName = "VideoPlayer"
    version = '3.1.3-FORGE-1.18.X'
}

// Mojang ships Java 17 to end users in 1.18+, so your mod should target Java 17.
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {
    mappings channel: 'parchment', version: '2022.11.06-1.18.2'
    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            property 'log4j.appender.Console', "org.apache.log4j.ConsoleAppender"
            property 'terminal.jline', 'true'
            arg '--nogui'

            mods {
                "videoplayer" {
                    source sourceSets.main
                }
            }
        }

        client {}
        server {}
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url "https://maven.tterrag.com/" }
    maven {
        url 'https://www.cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url 'https://jitpack.io' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.18.2-40.3.10'

    implementation 'com.github.WaterMediaTeam:watermedia:2.1.22'
    implementation fg.deobf("curse.maven:jei-238222:4434393")
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "videoplayer",
                "Specification-Vendor"    : "Goedix",
                "Specification-Version"   : project.version, // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "Goedix",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
