# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.1
mappings_channel=parchment
mappings_version=2024.11.17
loader_version=0.16.10

# Mod Properties
mod_version = 3.0.5
modid = videoplayer
maven_group = com.github.ngoedix
archives_base_name = VideoPlayer-3.0.5-FABRIC-1.21.X

# Dependencies
fabric_version=0.115.0+1.21.1